### ISSUE TITLE
working on OWA but not loading in desktop client

### ISSUE THREAD

**Issue by nitslucky** [OfficeDev/Outlook-Add-In-Contextual-Regex#1]
Hi, 
I tried this add in combination with angular app, its working fine as it says but only in OWA. But its not getting loaded in Desktop Client. Is there something which needs to be done in manifest file to make it run in the outlook desktop client.

Thanks

**Comment by r-puri** [comment]
Hi,
The highlighting works in OWA (outlook.com) but does not work in the desktop client. The order number is detected in the desktop client and the add-in bar appears , but the order number is not highlighted. However on the web client the highlight and the add-in bar works fine. Any ideas?

Thanks
Desktop client: No highlight : Mac outlook 16.11
![image](https://user-images.githubusercontent.com/30421742/38214114-788dd13a-3678-11e8-9d9c-02da76d30b85.png)

Web client : With Highligth
![image](https://user-images.githubusercontent.com/30421742/38214190-ba7fee8e-3678-11e8-87ea-74d5704648f2.png)

**Comment by nitslucky** [comment]
Hi, 
Did you do some changes in the manifest file? Or can you please share the code? Because in my case its only loading on exchange server. It doesn't appear in the add-in bar in desktop client not even in windows. But I can see the add-in manifest file is listed in Manifest folder: C:\Users\{username}\AppData\Local\Microsoft\Office\16.0\Wef\{96571F64-B6B1-4898-A500-3DC4952F5FFA}\2o0JcQKAvdECaRQnqB8vGQ==\Manifests 

Thanks

**Comment by jasonjoh** [comment]
When I wrote this sample this was only working in the web client, the desktop client had not yet fully implemented this. Let me double-check with the Outlook team to see where they are with this.

**Comment by r-puri** [comment]
@jasonjoh thanks.
Some more updates:
1. It works well in outlook web & outlook 2016 client on windows 10. I installed this on my @hotmail.com account at outlook.com and then the add-in was available seamlessly on my outlook client on windows.

2. It works partially for outlook 2016 on mac. As you can see my earlier screen shot, it does not highlight the order number in the body, but brings up the add-in bar when viewing the email message. When I click on the add-in bar it shows no matches in the add-in pop up window. (screens below for mac).

[manifest.xml.zip](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex/files/1872559/manifest.xml.zip)

@nitslucky, I am attaching the manifest file. I did not make substantial changes to the manifest file.

MAC CLIENT SCREEN: ORDER NUMBER NOT HIGHLIGHTED but the add-in bar appears
![image](https://user-images.githubusercontent.com/30421742/38264079-c9562fa0-3726-11e8-9423-5bc802498027.png)

MAC CLIENT SCREEN: After you click on the add-in bar , the pop up screen does not show the match but now highlights the order number

![image](https://user-images.githubusercontent.com/30421742/38264212-2e5a5106-3727-11e8-87ce-2207f0cd2f7b.png)

**Comment by jasonjoh** [comment]
@r-puri Yep, ok, that's expected. Mac is still using the old method, so you get the add-in bar instead of the inline highlight.

@nitslucky There was a recent rollback with Outlook desktop (on Windows) that impacts this. If you're not seeing it at all, you may not have a click-to-run install (the Office 365 version of Office 2016)?

**Comment by nitslucky** [comment]
@r-puri Thanks for sharing the manifest file. I checked it and I didn't see many changes except the urls.

@jasonjoh Yes i am not seeing the addin at all on outlook desktop. Yes i have click to run install. But I was reading the documents and it says DetectedEntity is only supported by Outlook on the web in Office 365. https://dev.office.com/reference/add-ins/manifest/extensionpoint

**Comment by nitslucky** [comment]
Hi @jasonjoh any updates to make the add-in work with Outlook Desktop on windows?

**Comment by jasonjoh** [comment]
@wamaina can you provide details on expectations for desktop?

@nitslucky It works for me in my Outlook 2016 on Windows, but I'm using pre-release versions :). I don't know the current status of what is publicly released.

**Comment by nitslucky** [comment]
I have Version 1710 build 8625.2127. Do I need to update this to a more recent version to make it work?
![image](https://user-images.githubusercontent.com/23555070/38556079-ab907c76-3cc8-11e8-83f6-e093b4d538f1.png)

Thanks

**Comment by imovertheinternet** [comment]
@nitslucky did you ever manage to get this working on the native Outlook application? "DetectedEntity" is only working on OWA for me.

**Comment by nitslucky** [comment]
@imovertheinternet no just on OWA.

**Comment by ElizabethSamuel-MSFT** [comment]
@nitslucky @r-puri @imovertheinternet Contextual add-ins should now be available in Windows and Mac. See [related documentation article](https://docs.microsoft.com/office/dev/add-ins/outlook/contextual-outlook-add-ins).

Let us know if you're still facing issues with this.

Thanks.
