### ISSUE TITLE
Change addin-bar name dynamically with code?

### ISSUE THREAD

**Issue by nitslucky** [OfficeDev/Outlook-Add-In-Contextual-Regex#2]
Hello, 

Is it possible to change the addin-bar name dynamically using code based on some response from the rest api instead of a fix DefaultValue in the manifest.xml file?

![addin-bar-name](https://user-images.githubusercontent.com/23555070/38410779-c6ad6514-3985-11e8-8788-f3449993c42c.PNG)

Thanks

**Comment by jasonjoh** [comment]
No, this isn't possible.
