### ISSUE TITLE
Problem with getSelectedRegExMatches

### ISSUE THREAD

**Issue by random65537** [OfficeDev/Outlook-Add-In-Contextual-Regex#3]
I'm following [this Github sample][1] and getSelectedRegExMatches returns null. 

Does the `requirement set`, as defined in the manifest, enable certain javascript functions or simply act as a filter as to which outlook clients or browsers `getSelectedRegExMatches` will run on?

How can I be sure that my OfficeDev environment will execute `getSelectedRegExMatches` and return data?

If it helps my regex is: `[a-z][a-z][a-z]\d\d\d` 

  [1]: https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex

**Comment by jgalentine007** [comment]
I am also having problems with this - getSelectedRegExMatches returns nothing when I run this add-in. I was experience the same problem with my own code. Running latest Google Chrome.
![Capture](https://user-images.githubusercontent.com/10709903/55516437-7438b780-562a-11e9-802f-9fbcd9ce79db.PNG)

**Comment by ElizabethSamuel-MSFT** [comment]
@random65537 @jgalentine007 Thanks for raising this.

You can also try this API in [Script Lab](https://docs.microsoft.com/office/dev/add-ins/overview/explore-with-script-lab): https://github.com/OfficeDev/office-js-snippets/blob/master/samples/outlook/75-entities-and-regex-matches/selected.yaml

If you're still facing this issue, let us know.

Thanks.
