### ISSUE TITLE
This still doesn't work on the Mac Desktop Client. I have my own add in that does not work there either although it works in Office 365 and Windows desktop client. 

### ISSUE THREAD

**Issue by jabelman** [OfficeDev/Outlook-Add-In-Contextual-Regex#5]
This still doesn't work on the Mac Desktop Client. I have my own add in that does not work there either although it works in Office 365 and Windows desktop client.

**Comment by alex--thomas** [comment]
Not working on my Outlook for Mac v16.40 (20073000) Desktop either.

Followed the side-loading instructions (and I'm a very experienced IT Pro), but it just hasn't worked.

**Comment by ElizabethSamuel-MSFT** [comment]
@alex--thomas Can you check if you're on the [new Mac UI](https://docs.microsoft.com/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview)? Contextual add-ins don't yet work on the new Mac UI.

**Comment by ElizabethSamuel-MSFT** [comment]
@jabelman @alex--thomas For current support, see the [documentation article](https://docs.microsoft.com/office/dev/add-ins/outlook/contextual-outlook-add-ins) for this feature.

Let us know if this still doesn't work for you.

Thanks.
