### ISSUE TITLE
In case of multiple order numbers it is giving same result for selected order number for each line

### ISSUE THREAD

**Issue by niteeshkr20** [OfficeDev/Outlook-Add-In-Contextual-Regex#7]
After cloning this project when i am sideloading this on my outlook and testing for below message body.I am getting same selected order number in both the cases i.e.  **CO-123456789** 

`Order number ios CO-123456789 and CO-987654321`

**NOTE** -  Running code without making any changes on my own.

**Comment by ElizabethSamuel-MSFT** [comment]
@niteeshkr20 Sorry to hear you're hitting an issue.

I tried this in Edge and the add-in seems to be working correctly. Can you share more about your configuration (e.g., OS for desktop versions, browser for web version)?

![image](https://user-images.githubusercontent.com/28541963/94299240-3ca78480-ff1c-11ea-8b26-59bf5decf0be.png)


Thanks.

**Comment by niteeshkr20** [comment]
Hi @ElizabethSamuel-MSFT 

It is now resolved.

The issue was with office-js library itself.
Please go through below issue - 
[https://github.com/OfficeDev/office-js/issues/1305](https://github.com/OfficeDev/office-js/issues/1305)
Thanks
